/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hotel.ui;

import Hotel.dao.NhanVienDAO;
import Hotel.entity.NhanVien;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class JpanelDanhSachBanBe extends javax.swing.JPanel {

    private String maNVKB;
    NhanVienDAO daoNV = new NhanVienDAO();
    private JpanelTrangChu trangChu;

    public JpanelDanhSachBanBe(JpanelTrangChu trangchu, String MNVKB) {
        this.trangChu = trangchu;
        this.maNVKB = MNVKB;
        initComponents();
        initData();
    }

    public void showinfo() {
        trangChu.showThongtinTinNhan(maNVKB);
    }

    public void initData() {
        try {
            NhanVien model = daoNV.findById(maNVKB);
            if (model != null) {
                if (model.getImg().equals("")) {
                    ImageIcon icon = new ImageIcon("src/Hotel/icon/profile.png");
                    Image originalImage1 = icon.getImage();
                    // Giảm kích thước hình ảnh
                    int newWidth = 50; // Kích thước mới
                    int newHeight = 50;
                    Image scaledImage1 = originalImage1.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

                    // Tạo ImageIcon mới từ hình ảnh đã giảm kích thước
                    ImageIcon scaledIcon1 = new ImageIcon(scaledImage1);

                    // Đặt biểu tượng mới vào JLabel
                    lblAvatar.setIcon(scaledIcon1);
                } else {
                    //set hình ảnh cho lbl
                    String linkImg2 = "src\\\\Hotel\\\\icon\\\\" + model.getImg();
                    ImageIcon icon = new ImageIcon(linkImg2); // lấy link ảnh
                    Image originalImage1 = icon.getImage();
                    // Giảm kích thước hình ảnh
                    int newWidth = 50; // Kích thước mới
                    int newHeight = 50;
                    Image scaledImage1 = originalImage1.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

                    // Tạo ImageIcon mới từ hình ảnh đã giảm kích thước
                    ImageIcon scaledIcon1 = new ImageIcon(scaledImage1);

                    // Đặt biểu tượng mới vào JLabel
                    lblAvatar.setIcon(scaledIcon1);
                }
                lblName.setText(model.getTenNV());

            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelView = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblTrangthai = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        JpanelView.setBackground(new java.awt.Color(255, 255, 255));
        JpanelView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpanelView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpanelViewMouseClicked(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Lê Minh Đức");
        lblName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameMouseClicked(evt);
            }
        });
        lblName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblNameKeyPressed(evt);
            }
        });

        lblTrangthai.setForeground(new java.awt.Color(0, 0, 0));
        lblTrangthai.setText("Hoạt động 15 phút trước");
        lblTrangthai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTrangthai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangthaiMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("...");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JpanelViewLayout = new javax.swing.GroupLayout(JpanelView);
        JpanelView.setLayout(JpanelViewLayout);
        JpanelViewLayout.setHorizontalGroup(
            JpanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelViewLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(JpanelViewLayout.createSequentialGroup()
                        .addComponent(lblTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpanelViewLayout.setVerticalGroup(
            JpanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelViewLayout.createSequentialGroup()
                        .addGroup(JpanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrangthai))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseClicked
        // TODO add your handling code here:
        showinfo();

    }//GEN-LAST:event_lblNameMouseClicked

    private void lblNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNameKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void lblTrangthaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangthaiMouseClicked
        // TODO add your handling code here:
        showinfo();

    }//GEN-LAST:event_lblTrangthaiMouseClicked

    private void lblAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarMouseClicked
        // TODO add your handling code here:
        showinfo();

    }//GEN-LAST:event_lblAvatarMouseClicked

    private void JpanelViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpanelViewMouseClicked
        // TODO add your handling code here:
        showinfo();

    }//GEN-LAST:event_JpanelViewMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        showinfo();

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTrangthai;
    // End of variables declaration//GEN-END:variables
}
